title: Behavior Referral Tracker
author: John Boniello
email: johnboniello@gmail.com
show_downloads: "true"
description: site for tracker
twitter_username: johnboniello
github_username:  johnboniello

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
